# Generated by Django 3.2.16 on 2022-11-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20221028_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fileupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('imgfile', models.ImageField(blank=True, null=True, upload_to='')),
                ('create_date', models.DateTimeField()),
            ],
        ),
    ]
