# Generated by Django 3.2.16 on 2022-11-15 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_fileupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='subject',
            new_name='title',
        ),
    ]
